
--GENERATED CLIENTS:

EXEC dodaj_klient_firma 'Activmed', '+48174033859', 'Mickiewicza 41', 'Czestochowa', '54-644', Polska, '6226262950';
EXEC dodaj_klient_firma 'Activity', '+48445505472', 'Popiełuszki 0', 'Jaworzna', '53-000', Polska, '8433696594';
EXEC dodaj_klient_firma 'Vodafone', '+48405931420', 'Słowackiego 63', 'Ujastek', '29-688', Polska, '2958636613';
EXEC dodaj_klient_firma 'Nokia', '+48502759138', 'Słowackiego 11', 'Czestochowa', '41-671', Polska, '8033780635';
EXEC dodaj_klient_prywatny 'Elzbieta Ratajczak', '+48160517525', 'Łąkowa 45', 'Gdańsk', '80-947', Polska, '315105';
EXEC dodaj_klient_prywatny 'Halina Stankiewicz', '+48969338723', 'Konopnickiej 63', 'Piekary', '13-107', Polska, NULL;
EXEC dodaj_klient_prywatny 'Paweł Przybysz', '+48316954689', 'Dobrowolska 104', 'Bukowina Tatrzanska', '29-034', Polska, NULL;
EXEC dodaj_klient_prywatny 'Jolanta Stepien', '+48503608716', 'Słonecznikowa 24', 'Ujastek', '15-529', Polska, '408395';
EXEC dodaj_klient_prywatny 'Krzysztof Mazur', '+48024326095', 'Bobrowskiego 54', 'Poznan', '92-351', Polska, NULL;
EXEC dodaj_klient_firma 'Samsung', '+48796788454', 'Leśna 111', 'Podzamcze', '67-534', Polska, '8649487037';
EXEC dodaj_klient_prywatny 'Henryk Sowa', '+48459077881', 'Reymana 57', 'Przemysl', '16-716', Polska, NULL;
EXEC dodaj_klient_prywatny 'Grażyna Adamczyk', '+48797192546', 'Konopnickiej 59', 'Bukowina Tatrzanska', '68-583', Polska, '644109';
EXEC dodaj_klient_firma 'Microsoft', '+48996694543', 'Słonecznikowa 1', 'Bydgoszcz', '39-381', Polska, '2096388670';
EXEC dodaj_klient_firma 'Audi', '+48179344669', 'Lipowa 79', 'Szczecin', '14-025', Polska, '9487489425';
EXEC dodaj_klient_prywatny 'Dariusz Dziedzic', '+48335415775', 'Dobrowolska 78', 'Ujastek', '01-904', Polska, NULL;
EXEC dodaj_klient_prywatny 'Teresa Żak', '+48748306862', 'Lipowa 65', 'Szczecin', '38-192', Polska, '643744';
EXEC dodaj_klient_prywatny 'Marianna Michalak', '+48725885172', 'Kwiatowa 104', 'Piekary', '95-875', Polska, NULL;
EXEC dodaj_klient_prywatny 'Halina Kubiak', '+48885252518', 'Dobrowolska 17', 'Bukowina Tatrzanska', '72-568', Polska, NULL;
EXEC dodaj_klient_firma 'Fiat', '+48959067817', 'Bobrowa 108', 'Gdańsk', '89-646', Polska, '4843282253';
EXEC dodaj_klient_prywatny 'Rafał Przybysz', '+48479965116', 'Kwiatowa 31', 'Laskowa', '21-967', Polska, NULL;
EXEC dodaj_klient_firma 'LG', '+48279613247', 'Bobrowa 25', 'Poznan', '50-408', Polska, '9478943458';
EXEC dodaj_klient_firma 'Nike', '+48313646145', 'Lipowa 49', 'Gdynia', '83-536', Polska, '0203642141';
EXEC dodaj_klient_prywatny 'Tomasz Pająk', '+48042413288', 'Konopnickiej 15', 'Kołobrzeg', '18-692', Polska, NULL;
EXEC dodaj_klient_prywatny 'Łukasz Piątek', '+48286537989', 'Słoneczna 60', 'Wieliczka', '73-119', Polska, NULL;
EXEC dodaj_klient_prywatny 'Monika Leśniak', '+48062837081', 'Lipowa 4', 'Gdynia', '37-768', Polska, NULL;
EXEC dodaj_klient_prywatny 'Małgorzata Bednarek', '+48420544463', 'Kwiatowa 3', 'Laskowa', '04-349', Polska, NULL;
EXEC dodaj_klient_prywatny 'Rafał Kania', '+48560777356', 'Lipowa 5', 'Podzamcze', '99-881', Polska, NULL;
EXEC dodaj_klient_prywatny 'Jacek Kozak', '+48335726070', 'Brzozowa 54', 'Ujastek', '87-595', Polska, NULL;
EXEC dodaj_klient_firma 'Citroen', '+48258719585', 'Lipowa 90', 'Krakow', '98-129', Polska, '3737271085';
EXEC dodaj_klient_firma 'H&M', '+48945995494', 'Dobrowolska 26', 'Szczecin', '44-376', Polska, '9466888958';
EXEC dodaj_klient_firma 'LuxMed', '+48838823032', 'Łąkowa 98', 'Przemysl', '12-754', Polska, '7576643165';
EXEC dodaj_klient_firma 'Hp', '+48872403298', 'Leśna 0', 'Warszawa', '59-590', Polska, '9528981700';
EXEC dodaj_klient_firma 'Apple', '+48473100029', 'Konopnickiej 38', 'Inowroclaw', '54-935', Polska, '3569925317';
EXEC dodaj_klient_firma 'Siemens', '+48315391057', 'Kościuszki 32', 'Szczecin', '91-195', Polska, '9873669844';
EXEC dodaj_klient_firma 'Orlen', '+48251970543', 'Krótka 73', 'Poznan', '03-243', Polska, '5447192254';
EXEC dodaj_klient_firma 'Shell', '+48949661437', 'Krótka 45', 'Bukowina Tatrzanska', '74-717', Polska, '9314910903';
EXEC dodaj_klient_prywatny 'Marek Małek', '+48871116923', 'Dobrowolska 51', 'Inowroclaw', '16-672', Polska, NULL;
EXEC dodaj_klient_prywatny 'Natalia Kaczmarek', '+48359669660', 'Kopernika 60', 'Zamosc', '99-126', Polska, NULL;
EXEC dodaj_klient_prywatny 'Małgorzata Blaszczyk', '+48075983845', 'Słowackiego 95', 'Zakopane', '86-120', Polska, NULL;
EXEC dodaj_klient_firma 'Empik', '+48173314772', 'Reymana 90', 'Gdańsk', '76-697', Polska, '4723522909';
EXEC dodaj_klient_prywatny 'Jolanta Stasiak', '+48984905989', 'Lipowa 24', 'Kielce', '79-495', Polska, '316486';
EXEC dodaj_klient_prywatny 'Michal Klimek', '+48073722895', 'Rynek główny 5', 'Gdańsk', '54-048', Polska, NULL;
EXEC dodaj_klient_prywatny 'Iwona Adamczyk', '+48602182983', 'Czarnowiejska 72', 'Szczecin', '03-104', Polska, NULL;
EXEC dodaj_klient_firma 'Filmweb', '+48464732048', 'Bobrowskiego 48', 'Niepolomice', '56-069', Polska, '0434443304';
EXEC dodaj_klient_firma 'Gazeta', '+48067670944', 'Łąkowa 70', 'Jaworzna', '10-822', Polska, '5094021610';
EXEC dodaj_klient_prywatny 'Stanisław Olejniczak', '+48866994497', 'Kopernika 82', 'Zamosc', '37-282', Polska, '249683';
EXEC dodaj_klient_prywatny 'Henryk Pawlik', '+48335357161', 'Leśna 77', 'Bukowina Tatrzanska', '38-711', Polska, NULL;
EXEC dodaj_klient_firma 'TVN', '+48620797854', 'Polna 47', 'Zakopane', '71-658', Polska, '2517935305';
EXEC dodaj_klient_firma 'Facebook', '+48447835617', 'Mickiewicza 95', 'Inowroclaw', '51-995', Polska, '9159695712';
EXEC dodaj_klient_firma 'Twitter', '+48122115558', 'Dobrowolska 85', 'Jaworzna', '82-191', Polska, '9122430529';
EXEC dodaj_klient_prywatny 'Piotr Polak', '+48990099063', 'Polna 36', 'Piekary', '83-610', Polska, NULL;
EXEC dodaj_klient_prywatny 'Danuta Nowak', '+48335402539', 'Słonecznikowa 71', 'Szczecin', '29-200', Polska, NULL;
EXEC dodaj_klient_firma 'Google', '+48893395678', 'Mickiewicza 32', 'Ujastek', '98-220', Polska, '9133710366';
EXEC dodaj_klient_prywatny 'Marek Kolodziej', '+48940222269', 'Kwiatowa 112', 'Warszawa', '76-939', Polska, NULL;
EXEC dodaj_klient_prywatny 'Michal Bak', '+48658464041', 'Bobrowskiego 29', 'Zamosc', '54-261', Polska, NULL;
EXEC dodaj_klient_prywatny 'Ryszard Czaja', '+48768520469', 'Polna 34', 'Jaworzna', '45-682', Polska, NULL;
EXEC dodaj_klient_firma 'Rzad RP', '+48280766295', 'Polna 10', 'Przemysl', '17-840', Polska, '3085500245';
EXEC dodaj_klient_firma 'Paramedics', '+48685262811', 'Dobrowolska 92', 'Bydgoszcz', '36-120', Polska, '3102689976';
EXEC dodaj_klient_prywatny 'Beata Kaczmarek', '+48378217975', 'Reymana 61', 'Zakopane', '82-471', Polska, '424288';
EXEC dodaj_klient_prywatny 'Kamil Kowalik', '+48846133962', 'Reymana 32', 'Bukowina Tatrzanska', '99-201', Polska, '094025';


--GENERATED PEOPLE:

EXEC dodaj_osoba 'Marcin', 'Jarosz', NULL;
EXEC dodaj_osoba 'Łukasz', 'Wojcik', NULL;
EXEC dodaj_osoba 'Rafał', 'Wojcik', NULL;
EXEC dodaj_osoba 'Tomasz', 'Sowa', NULL;
EXEC dodaj_osoba 'Anna', 'Bak', NULL;
EXEC dodaj_osoba 'Barbara', 'Tomczak', '765302';
EXEC dodaj_osoba 'Piotr', 'Kolodziej', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Kowalik', NULL;
EXEC dodaj_osoba 'Natalia', 'Czech', '788895';
EXEC dodaj_osoba 'Anna', 'Leśniak', NULL;
EXEC dodaj_osoba 'Agnieszka', 'Kaczmarek', NULL;
EXEC dodaj_osoba 'Stanisław', 'Dudek', '759299';
EXEC dodaj_osoba 'Kamil', 'Mazur', '755568';
EXEC dodaj_osoba 'Maciej', 'Kot', '388062';
EXEC dodaj_osoba 'Iwona', 'Michalak', NULL;
EXEC dodaj_osoba 'Mateusz', 'Bak', NULL;
EXEC dodaj_osoba 'Karolina', 'Ratajczak', '114564';
EXEC dodaj_osoba 'Jakub', 'Kaczmarczyk', NULL;
EXEC dodaj_osoba 'Ewa', 'Duda', NULL;
EXEC dodaj_osoba 'Marek', 'Polak', NULL;
EXEC dodaj_osoba 'Michal', 'Kazmierczak', '551049';
EXEC dodaj_osoba 'Grzegorz', 'Stepien', NULL;
EXEC dodaj_osoba 'Dorota', 'Kazmierczak', '321305';
EXEC dodaj_osoba 'Barbara', 'Jarosz', '977875';
EXEC dodaj_osoba 'Teresa', 'Kazmierczak', NULL;
EXEC dodaj_osoba 'Anna', 'Kopeć', NULL;
EXEC dodaj_osoba 'Zbigniew', 'Pawlik', '838263';
EXEC dodaj_osoba 'Joanna', 'Pietrzak', NULL;
EXEC dodaj_osoba 'Iwona', 'Zięba', NULL;
EXEC dodaj_osoba 'Grzegorz', 'Bednarek', '076652';
EXEC dodaj_osoba 'Jan', 'Wrobel', '015595';
EXEC dodaj_osoba 'Zofia', 'Wieczorek', NULL;
EXEC dodaj_osoba 'Jan', 'Przybysz', NULL;
EXEC dodaj_osoba 'Wojciech', 'Stasiak', NULL;
EXEC dodaj_osoba 'Marianna', 'Kruk', NULL;
EXEC dodaj_osoba 'Kamil', 'Kania', NULL;
EXEC dodaj_osoba 'Paweł', 'Mazur', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Kazmierczak', NULL;
EXEC dodaj_osoba 'Jacek', 'Piątek', NULL;
EXEC dodaj_osoba 'Elzbieta', 'Cieslak', '208361';
EXEC dodaj_osoba 'Anna', 'Pająk', '989481';
EXEC dodaj_osoba 'Jerzy', 'Kaczmarek', NULL;
EXEC dodaj_osoba 'Irena', 'Ratajczak', NULL;
EXEC dodaj_osoba 'Piotr', 'Duda', NULL;
EXEC dodaj_osoba 'Elzbieta', 'Kowalik', NULL;
EXEC dodaj_osoba 'Krystyna', 'Tomczak', NULL;
EXEC dodaj_osoba 'Krystyna', 'Kowalik', '116811';
EXEC dodaj_osoba 'Karolina', 'Kolodziej', NULL;
EXEC dodaj_osoba 'Iwona', 'Dudek', '824216';
EXEC dodaj_osoba 'Anna', 'Polak', NULL;
EXEC dodaj_osoba 'Natalia', 'Olejniczak', NULL;
EXEC dodaj_osoba 'Piotr', 'Polak', '636150';
EXEC dodaj_osoba 'Józef', 'Urban', NULL;
EXEC dodaj_osoba 'Kamil', 'Kazmierczak', '162445';
EXEC dodaj_osoba 'Teresa', 'Wilk', '644794';
EXEC dodaj_osoba 'Ryszard', 'Piątek', NULL;
EXEC dodaj_osoba 'Paweł', 'Zajac', NULL;
EXEC dodaj_osoba 'Ryszard', 'Cieslak', NULL;
EXEC dodaj_osoba 'Anna', 'Dudek', NULL;
EXEC dodaj_osoba 'Jadwiga', 'Kubiak', NULL;
EXEC dodaj_osoba 'Agnieszka', 'Lis', NULL;
EXEC dodaj_osoba 'Łukasz', 'Mucha', '139880';
EXEC dodaj_osoba 'Grzegorz', 'Świątek', '709544';
EXEC dodaj_osoba 'Ewa', 'Blaszczyk', NULL;
EXEC dodaj_osoba 'Jerzy', 'Kruk', NULL;
EXEC dodaj_osoba 'Marta', 'Marciniak', NULL;
EXEC dodaj_osoba 'Tadeusz', 'Olejniczak', NULL;
EXEC dodaj_osoba 'Dariusz', 'Stankiewicz', '226551';
EXEC dodaj_osoba 'Stanisław', 'Małek', NULL;
EXEC dodaj_osoba 'Marcin', 'Zajac', NULL;
EXEC dodaj_osoba 'Monika', 'Kozak', NULL;
EXEC dodaj_osoba 'Natalia', 'Kozak', NULL;
EXEC dodaj_osoba 'Ryszard', 'Duda', NULL;
EXEC dodaj_osoba 'Jan', 'Lis', NULL;
EXEC dodaj_osoba 'Marcin', 'Tomczak', NULL;
EXEC dodaj_osoba 'Tomasz', 'Kubiak', NULL;
EXEC dodaj_osoba 'Beata', 'Małek', NULL;
EXEC dodaj_osoba 'Krzysztof', 'Klimek', '411720';
EXEC dodaj_osoba 'Adam', 'Cieslak', '400852';
EXEC dodaj_osoba 'Zbigniew', 'Lis', NULL;
EXEC dodaj_osoba 'Maciej', 'Matysiak', NULL;
EXEC dodaj_osoba 'Robert', 'Jarosz', NULL;
EXEC dodaj_osoba 'Jan', 'Mazur', NULL;
EXEC dodaj_osoba 'Karolina', 'Marciniak', '177795';
EXEC dodaj_osoba 'Katarzyna', 'Adamczyk', NULL;
EXEC dodaj_osoba 'Monika', 'Stankiewicz', '497996';
EXEC dodaj_osoba 'Marianna', 'Stasiak', '070859';
EXEC dodaj_osoba 'Paweł', 'Kowalik', '908318';
EXEC dodaj_osoba 'Joanna', 'Kasprzyk', NULL;
EXEC dodaj_osoba 'Jacek', 'Cieslak', NULL;
EXEC dodaj_osoba 'Mariusz', 'Kowalik', NULL;
EXEC dodaj_osoba 'Małgorzata', 'Czech', '405023';
EXEC dodaj_osoba 'Joanna', 'Kruk', '935718';
EXEC dodaj_osoba 'Agnieszka', 'Kubiak', '564106';
EXEC dodaj_osoba 'Natalia', 'Adamczyk', NULL;
EXEC dodaj_osoba 'Małgorzata', 'Zięba', NULL;
EXEC dodaj_osoba 'Marek', 'Tomczak', NULL;
EXEC dodaj_osoba 'Barbara', 'Kaczmarek', '858376';
EXEC dodaj_osoba 'Robert', 'Polak', NULL;
EXEC dodaj_osoba 'Beata', 'Kot', NULL;
EXEC dodaj_osoba 'Natalia', 'Kubiak', '165453';
EXEC dodaj_osoba 'Andrzej', 'Kaczmarczyk', NULL;
EXEC dodaj_osoba 'Grzegorz', 'Kaczmarczyk', NULL;
EXEC dodaj_osoba 'Jerzy', 'Wilk', NULL;
EXEC dodaj_osoba 'Karolina', 'Wilk', NULL;
EXEC dodaj_osoba 'Natalia', 'Małek', '804467';
EXEC dodaj_osoba 'Robert', 'Sowa', NULL;
EXEC dodaj_osoba 'Rafał', 'Pawlik', NULL;
EXEC dodaj_osoba 'Grażyna', 'Lis', NULL;
EXEC dodaj_osoba 'Beata', 'Matysiak', NULL;
EXEC dodaj_osoba 'Halina', 'Nowak', NULL;
EXEC dodaj_osoba 'Dorota', 'Wrobel', NULL;
EXEC dodaj_osoba 'Jacek', 'Małek', NULL;
EXEC dodaj_osoba 'Maciej', 'Cieslak', '177643';
EXEC dodaj_osoba 'Agnieszka', 'Klimek', NULL;
EXEC dodaj_osoba 'Robert', 'Kot', NULL;
EXEC dodaj_osoba 'Jacek', 'Szewczyk', '120467';
EXEC dodaj_osoba 'Monika', 'Adamczyk', '047473';
EXEC dodaj_osoba 'Mateusz', 'Leśniak', NULL;
EXEC dodaj_osoba 'Stanisław', 'Marciniak', '361074';
EXEC dodaj_osoba 'Ewa', 'Kaczmarek', '729814';
EXEC dodaj_osoba 'Katarzyna', 'Polak', '535268';
EXEC dodaj_osoba 'Natalia', 'Bednarek', NULL;
EXEC dodaj_osoba 'Jan', 'Zięba', '350570';
EXEC dodaj_osoba 'Kazimierz', 'Kolodziej', NULL;
EXEC dodaj_osoba 'Ryszard', 'Kasprzyk', NULL;
EXEC dodaj_osoba 'Aleksandra', 'Nowak', NULL;
EXEC dodaj_osoba 'Grzegorz', 'Cieslak', '069513';
EXEC dodaj_osoba ' Maria', 'Stankiewicz', NULL;
EXEC dodaj_osoba 'Maciej', 'Pająk', '010091';
EXEC dodaj_osoba 'Paweł', 'Kruk', '671661';
EXEC dodaj_osoba 'Michal', 'Stasiak', '100110';
EXEC dodaj_osoba 'Michal', 'Polak', '601430';
EXEC dodaj_osoba 'Wojciech', 'Wojcik', '010903';
EXEC dodaj_osoba 'Jan', 'Adamczyk', NULL;
EXEC dodaj_osoba 'Józef', 'Michalak', '445539';
EXEC dodaj_osoba 'Michal', 'Piątek', NULL;
EXEC dodaj_osoba 'Józef', 'Kania', NULL;
EXEC dodaj_osoba 'Barbara', 'Jarosz', NULL;
EXEC dodaj_osoba 'Joanna', 'Kozak', '140182';
EXEC dodaj_osoba 'Danuta', 'Koziol', '472367';
EXEC dodaj_osoba 'Józef', 'Kazmierczak', '370563';
EXEC dodaj_osoba 'Anna', 'Klimek', NULL;
EXEC dodaj_osoba 'Jolanta', 'Olejniczak', NULL;
EXEC dodaj_osoba 'Jerzy', 'Kruk', NULL;
EXEC dodaj_osoba 'Anna', 'Kowalik', NULL;
EXEC dodaj_osoba 'Mariusz', 'Dudek', NULL;
EXEC dodaj_osoba 'Janina', 'Baran', '780013';
EXEC dodaj_osoba ' Maria', 'Duda', NULL;
EXEC dodaj_osoba 'Jacek', 'Matysiak', NULL;
EXEC dodaj_osoba 'Barbara', 'Stepien', NULL;
EXEC dodaj_osoba 'Teresa', 'Piątek', NULL;
EXEC dodaj_osoba 'Grzegorz', 'Kazmierczak', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Wieczorek', '910008';
EXEC dodaj_osoba 'Halina', 'Ratajczak', '512482';
EXEC dodaj_osoba 'Marianna', 'Kozak', NULL;
EXEC dodaj_osoba ' Maria', 'Kubiak', NULL;
EXEC dodaj_osoba ' Maria', 'Stasiak', NULL;
EXEC dodaj_osoba 'Robert', 'Mroz', '053939';
EXEC dodaj_osoba ' Maria', 'Kania', NULL;
EXEC dodaj_osoba 'Helena', 'Kania', NULL;
EXEC dodaj_osoba 'Adam', 'Kaczmarek', '184018';
EXEC dodaj_osoba 'Ewa', 'Wojcik', '350542';
EXEC dodaj_osoba 'Jakub', 'Mazur', NULL;
EXEC dodaj_osoba 'Jerzy', 'Pająk', NULL;
EXEC dodaj_osoba 'Andrzej', 'Wieczorek', NULL;
EXEC dodaj_osoba 'Jerzy', 'Kazmierczak', '228772';
EXEC dodaj_osoba 'Maciej', 'Kolodziej', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Zięba', NULL;
EXEC dodaj_osoba 'Elzbieta', 'Wieczorek', NULL;
EXEC dodaj_osoba 'Józef', 'Zajac', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Cieslak', NULL;
EXEC dodaj_osoba 'Joanna', 'Żak', NULL;
EXEC dodaj_osoba 'Barbara', 'Czaja', NULL;
EXEC dodaj_osoba 'Paweł', 'Żak', NULL;
EXEC dodaj_osoba 'Karolina', 'Walczak', NULL;
EXEC dodaj_osoba 'Jakub', 'Kasprzyk', NULL;
EXEC dodaj_osoba 'Dorota', 'Czaja', NULL;
EXEC dodaj_osoba 'Wojciech', 'Przybysz', '985450';
EXEC dodaj_osoba 'Magdalena', 'Wojcik', NULL;
EXEC dodaj_osoba 'Danuta', 'Kazmierczak', '676603';
EXEC dodaj_osoba 'Mariusz', 'Dudek', NULL;
EXEC dodaj_osoba 'Kamil', 'Kubiak', '649792';
EXEC dodaj_osoba 'Marta', 'Baran', NULL;
EXEC dodaj_osoba 'Robert', 'Blaszczyk', NULL;
EXEC dodaj_osoba 'Anna', 'Mazur', '986686';
EXEC dodaj_osoba 'Agnieszka', 'Leśniak', NULL;
EXEC dodaj_osoba 'Stanisław', 'Żak', NULL;
EXEC dodaj_osoba 'Katarzyna', 'Baran', '673803';
EXEC dodaj_osoba 'Andrzej', 'Bak', NULL;
EXEC dodaj_osoba ' Maria', 'Kurek', '101666';
EXEC dodaj_osoba 'Janina', 'Tomczyk', '493517';
EXEC dodaj_osoba 'Halina', 'Walczak', NULL;
EXEC dodaj_osoba 'Jacek', 'Adamczyk', NULL;
EXEC dodaj_osoba 'Kamil', 'Wlodarczyk', NULL;
EXEC dodaj_osoba 'Józef', 'Leśniak', '535831';
EXEC dodaj_osoba 'Joanna', 'Duda', NULL;
EXEC dodaj_osoba 'Monika', 'Adamczyk', NULL;
EXEC dodaj_osoba 'Danuta', 'Kowalik', '883973';
EXEC dodaj_osoba 'Adam', 'Matysiak', NULL;
EXEC dodaj_osoba 'Natalia', 'Olejniczak', NULL;
EXEC dodaj_osoba 'Natalia', 'Olejniczak', NULL;
EXEC dodaj_osoba 'Henryk', 'Wilk', NULL;
EXEC dodaj_osoba 'Rafał', 'Tomczyk', NULL;
EXEC dodaj_osoba 'Karolina', 'Wozniak', '902358';
EXEC dodaj_osoba 'Grażyna', 'Piątek', NULL;
EXEC dodaj_osoba 'Józef', 'Wlodarczyk', NULL;
EXEC dodaj_osoba 'Aleksandra', 'Żak', NULL;
EXEC dodaj_osoba 'Tomasz', 'Dziedzic', NULL;
EXEC dodaj_osoba 'Natalia', 'Walczak', NULL;
EXEC dodaj_osoba 'Jadwiga', 'Urban', NULL;
EXEC dodaj_osoba 'Marta', 'Walczak', NULL;
EXEC dodaj_osoba 'Teresa', 'Koziol', NULL;
EXEC dodaj_osoba 'Mateusz', 'Dziedzic', NULL;
EXEC dodaj_osoba 'Paweł', 'Adamczyk', NULL;
EXEC dodaj_osoba 'Andrzej', 'Wlodarczyk', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Tomczyk', NULL;
EXEC dodaj_osoba 'Jerzy', 'Wieczorek', NULL;
EXEC dodaj_osoba 'Krzysztof', 'Blaszczyk', NULL;
EXEC dodaj_osoba 'Barbara', 'Bak', '074003';
EXEC dodaj_osoba 'Halina', 'Jarosz', NULL;
EXEC dodaj_osoba 'Łukasz', 'Matysiak', NULL;
EXEC dodaj_osoba 'Michal', 'Piątek', NULL;
EXEC dodaj_osoba 'Jadwiga', 'Pawlik', '250224';
EXEC dodaj_osoba 'Dorota', 'Kaczmarczyk', '438178';
EXEC dodaj_osoba 'Anna', 'Kolodziej', '227424';
EXEC dodaj_osoba 'Paweł', 'Nowak', NULL;
EXEC dodaj_osoba 'Jolanta', 'Kaczmarek', NULL;
EXEC dodaj_osoba 'Tomasz', 'Kaczmarek', NULL;
EXEC dodaj_osoba 'Zbigniew', 'Sowa', '590544';
EXEC dodaj_osoba 'Halina', 'Leśniak', NULL;
EXEC dodaj_osoba 'Grzegorz', 'Stasiak', NULL;
EXEC dodaj_osoba 'Krzysztof', 'Wlodarczyk', '368509';
EXEC dodaj_osoba 'Tadeusz', 'Kaczmarek', NULL;
EXEC dodaj_osoba 'Robert', 'Pająk', '612970';
EXEC dodaj_osoba 'Wojciech', 'Urban', NULL;
EXEC dodaj_osoba ' Maria', 'Lis', NULL;
EXEC dodaj_osoba 'Maciej', 'Baran', NULL;
EXEC dodaj_osoba 'Marta', 'Czech', NULL;
EXEC dodaj_osoba 'Andrzej', 'Kozak', NULL;
EXEC dodaj_osoba 'Natalia', 'Kot', '614950';
EXEC dodaj_osoba 'Marta', 'Kaczmarczyk', '712710';
EXEC dodaj_osoba 'Marta', 'Polak', '440690';
EXEC dodaj_osoba 'Iwona', 'Walczak', NULL;
EXEC dodaj_osoba 'Tadeusz', 'Pająk', NULL;
EXEC dodaj_osoba 'Irena', 'Małek', '898713';
EXEC dodaj_osoba 'Józef', 'Olejniczak', NULL;
EXEC dodaj_osoba 'Dorota', 'Wlodarczyk', NULL;
EXEC dodaj_osoba 'Andrzej', 'Duda', NULL;
EXEC dodaj_osoba 'Mariusz', 'Blaszczyk', '752333';
EXEC dodaj_osoba 'Krystyna', 'Wlodarczyk', NULL;
EXEC dodaj_osoba 'Aleksandra', 'Olejniczak', '760773';
EXEC dodaj_osoba 'Janina', 'Szewczyk', NULL;
EXEC dodaj_osoba 'Grzegorz', 'Walczak', '551852';
EXEC dodaj_osoba 'Rafał', 'Bak', '173281';
EXEC dodaj_osoba 'Maciej', 'Kopeć', NULL;
EXEC dodaj_osoba 'Krzysztof', 'Matysiak', '352798';
EXEC dodaj_osoba 'Natalia', 'Blaszczyk', NULL;
EXEC dodaj_osoba 'Karolina', 'Kubiak', NULL;
EXEC dodaj_osoba 'Krzysztof', 'Zięba', '473877';
EXEC dodaj_osoba 'Henryk', 'Sowa', NULL;
EXEC dodaj_osoba 'Aleksandra', 'Mazur', NULL;
EXEC dodaj_osoba 'Krystyna', 'Kasprzyk', NULL;
EXEC dodaj_osoba 'Wojciech', 'Olejniczak', NULL;
EXEC dodaj_osoba 'Halina', 'Wrobel', '184424';
EXEC dodaj_osoba 'Joanna', 'Wlodarczyk', NULL;
EXEC dodaj_osoba 'Magdalena', 'Tomczak', NULL;
EXEC dodaj_osoba 'Agnieszka', 'Świątek', NULL;
EXEC dodaj_osoba 'Ryszard', 'Klimek', NULL;
EXEC dodaj_osoba 'Katarzyna', 'Krawczyk', NULL;
EXEC dodaj_osoba 'Monika', 'Adamczyk', '401822';
EXEC dodaj_osoba 'Adam', 'Czech', NULL;
EXEC dodaj_osoba 'Marta', 'Kowalik', NULL;
EXEC dodaj_osoba 'Magdalena', 'Pietrzak', NULL;
EXEC dodaj_osoba 'Katarzyna', 'Kubiak', NULL;
EXEC dodaj_osoba 'Iwona', 'Kasprzyk', NULL;
EXEC dodaj_osoba 'Dorota', 'Kowalik', NULL;
EXEC dodaj_osoba 'Zbigniew', 'Mazur', NULL;
EXEC dodaj_osoba 'Magdalena', 'Tomczyk', '569932';
EXEC dodaj_osoba 'Beata', 'Tomczyk', NULL;
EXEC dodaj_osoba 'Agnieszka', 'Kaczmarczyk', NULL;
EXEC dodaj_osoba 'Jan', 'Czaja', '983866';
EXEC dodaj_osoba 'Elzbieta', 'Pawlik', NULL;
EXEC dodaj_osoba 'Marek', 'Olejniczak', NULL;
EXEC dodaj_osoba 'Helena', 'Zajac', NULL;
EXEC dodaj_osoba 'Aleksandra', 'Przybysz', NULL;
EXEC dodaj_osoba 'Ewa', 'Urban', '921180';
EXEC dodaj_osoba 'Zbigniew', 'Olejniczak', NULL;
EXEC dodaj_osoba 'Aleksandra', 'Dudek', NULL;
EXEC dodaj_osoba 'Jacek', 'Wlodarczyk', '049284';
EXEC dodaj_osoba 'Michal', 'Wojcik', NULL;
EXEC dodaj_osoba 'Mateusz', 'Olejniczak', '922082';
EXEC dodaj_osoba 'Ryszard', 'Lis', NULL;
EXEC dodaj_osoba 'Marianna', 'Klimek', NULL;
EXEC dodaj_osoba 'Magdalena', 'Wieczorek', NULL;
EXEC dodaj_osoba 'Dariusz', 'Zięba', '286774';
EXEC dodaj_osoba 'Jakub', 'Stasiak', '375414';
EXEC dodaj_osoba 'Grażyna', 'Sowa', '388867';
EXEC dodaj_osoba 'Tomasz', 'Leśniak', NULL;
EXEC dodaj_osoba 'Tomasz', 'Krawczyk', NULL;
EXEC dodaj_osoba 'Paweł', 'Bednarek', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Wieczorek', NULL;
EXEC dodaj_osoba 'Marcin', 'Adamczyk', '900966';
EXEC dodaj_osoba 'Jolanta', 'Wozniak', NULL;
EXEC dodaj_osoba 'Aleksandra', 'Zajac', NULL;
EXEC dodaj_osoba ' Maria', 'Przybysz', NULL;
EXEC dodaj_osoba 'Anna', 'Kaczmarek', '241161';
EXEC dodaj_osoba 'Katarzyna', 'Baran', NULL;
EXEC dodaj_osoba 'Zofia', 'Zajac', NULL;
EXEC dodaj_osoba 'Zbigniew', 'Duda', NULL;
EXEC dodaj_osoba 'Krystyna', 'Świątek', NULL;
EXEC dodaj_osoba 'Stanisław', 'Wozniak', '597178';
EXEC dodaj_osoba 'Janina', 'Lis', NULL;
EXEC dodaj_osoba 'Danuta', 'Cieslak', '406611';
EXEC dodaj_osoba 'Jadwiga', 'Ratajczak', NULL;
EXEC dodaj_osoba 'Janina', 'Wrobel', NULL;
EXEC dodaj_osoba 'Tadeusz', 'Kaczmarek', '002241';
EXEC dodaj_osoba 'Marta', 'Duda', '378175';
EXEC dodaj_osoba 'Zofia', 'Kazmierczak', NULL;
EXEC dodaj_osoba 'Agnieszka', 'Krawczyk', NULL;
EXEC dodaj_osoba 'Jerzy', 'Stasiak', '629056';
EXEC dodaj_osoba 'Jerzy', 'Wilk', '727366';
EXEC dodaj_osoba 'Andrzej', 'Łuczak', '392842';
EXEC dodaj_osoba 'Kamil', 'Stepien', NULL;
EXEC dodaj_osoba 'Irena', 'Lis', NULL;
EXEC dodaj_osoba 'Marcin', 'Krawczyk', NULL;
EXEC dodaj_osoba 'Aleksandra', 'Wrobel', NULL;
EXEC dodaj_osoba 'Helena', 'Małek', NULL;
EXEC dodaj_osoba 'Grzegorz', 'Lis', '214678';
EXEC dodaj_osoba 'Krystyna', 'Nowak', '734824';
EXEC dodaj_osoba 'Janina', 'Stasiak', NULL;
EXEC dodaj_osoba 'Wojciech', 'Urban', NULL;
EXEC dodaj_osoba 'Wojciech', 'Kaczmarczyk', NULL;
EXEC dodaj_osoba 'Magdalena', 'Kolodziej', '481889';
EXEC dodaj_osoba 'Anna', 'Bednarek', NULL;
EXEC dodaj_osoba 'Mariusz', 'Kania', NULL;
EXEC dodaj_osoba 'Rafał', 'Marciniak', NULL;
EXEC dodaj_osoba 'Zofia', 'Przybysz', NULL;
EXEC dodaj_osoba 'Andrzej', 'Wilk', NULL;
EXEC dodaj_osoba 'Magdalena', 'Pająk', NULL;
EXEC dodaj_osoba 'Mateusz', 'Krawczyk', NULL;
EXEC dodaj_osoba 'Ewa', 'Cieslak', NULL;
EXEC dodaj_osoba 'Halina', 'Stankiewicz', NULL;
EXEC dodaj_osoba 'Irena', 'Kaczmarczyk', '078231';
EXEC dodaj_osoba 'Józef', 'Małek', '725520';
EXEC dodaj_osoba 'Jolanta', 'Pająk', NULL;
EXEC dodaj_osoba 'Łukasz', 'Kaczmarek', '461004';
EXEC dodaj_osoba 'Jacek', 'Stepien', NULL;
EXEC dodaj_osoba 'Marianna', 'Walczak', NULL;
EXEC dodaj_osoba 'Marta', 'Dudek', NULL;
EXEC dodaj_osoba 'Jerzy', 'Klimek', NULL;
EXEC dodaj_osoba 'Maciej', 'Mucha', '330794';
EXEC dodaj_osoba 'Helena', 'Marciniak', NULL;
EXEC dodaj_osoba 'Małgorzata', 'Tomczyk', NULL;
EXEC dodaj_osoba 'Ewa', 'Nowak', '354139';
EXEC dodaj_osoba 'Stanisław', 'Kasprzyk', NULL;
EXEC dodaj_osoba 'Krzysztof', 'Walczak', NULL;
EXEC dodaj_osoba 'Anna', 'Pietrzak', NULL;
EXEC dodaj_osoba 'Rafał', 'Jarosz', '198327';
EXEC dodaj_osoba 'Mariusz', 'Szewczyk', NULL;
EXEC dodaj_osoba ' Maria', 'Lis', '053305';
EXEC dodaj_osoba 'Monika', 'Polak', NULL;
EXEC dodaj_osoba 'Anna', 'Pająk', NULL;
EXEC dodaj_osoba 'Mariusz', 'Mroz', '540873';
EXEC dodaj_osoba 'Elzbieta', 'Kruk', NULL;
EXEC dodaj_osoba 'Krzysztof', 'Świątek', NULL;
EXEC dodaj_osoba 'Iwona', 'Wrobel', NULL;
EXEC dodaj_osoba 'Halina', 'Baran', NULL;
EXEC dodaj_osoba 'Teresa', 'Leśniak', NULL;
EXEC dodaj_osoba 'Krzysztof', 'Mroz', NULL;
EXEC dodaj_osoba 'Dorota', 'Zięba', '251503';
EXEC dodaj_osoba 'Marek', 'Wilk', NULL;
EXEC dodaj_osoba 'Monika', 'Matysiak', NULL;
EXEC dodaj_osoba 'Maciej', 'Kasprzyk', NULL;
EXEC dodaj_osoba 'Helena', 'Kozak', NULL;
EXEC dodaj_osoba 'Zofia', 'Tomczyk', '367143';
EXEC dodaj_osoba 'Tadeusz', 'Małek', NULL;
EXEC dodaj_osoba 'Jolanta', 'Kubiak', NULL;
EXEC dodaj_osoba 'Danuta', 'Kot', NULL;
EXEC dodaj_osoba 'Helena', 'Marciniak', NULL;
EXEC dodaj_osoba 'Jakub', 'Zięba', NULL;
EXEC dodaj_osoba 'Henryk', 'Lis', NULL;
EXEC dodaj_osoba 'Joanna', 'Wieczorek', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Mazur', NULL;
EXEC dodaj_osoba 'Rafał', 'Kubiak', NULL;
EXEC dodaj_osoba 'Paweł', 'Stankiewicz', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Wozniak', '551107';
EXEC dodaj_osoba 'Łukasz', 'Cieslak', NULL;
EXEC dodaj_osoba 'Aleksandra', 'Dziedzic', NULL;
EXEC dodaj_osoba 'Halina', 'Mazur', NULL;
EXEC dodaj_osoba 'Jadwiga', 'Kot', '142592';
EXEC dodaj_osoba 'Barbara', 'Baran', NULL;
EXEC dodaj_osoba 'Magdalena', 'Lis', NULL;
EXEC dodaj_osoba 'Marianna', 'Lis', NULL;
EXEC dodaj_osoba 'Grażyna', 'Mucha', NULL;
EXEC dodaj_osoba 'Robert', 'Blaszczyk', NULL;
EXEC dodaj_osoba 'Krystyna', 'Stasiak', NULL;
EXEC dodaj_osoba 'Aleksandra', 'Małek', NULL;
EXEC dodaj_osoba 'Krystyna', 'Lis', NULL;
EXEC dodaj_osoba 'Łukasz', 'Kolodziej', '252702';
EXEC dodaj_osoba 'Józef', 'Kot', NULL;
EXEC dodaj_osoba 'Jolanta', 'Kot', NULL;
EXEC dodaj_osoba 'Marta', 'Kopeć', NULL;
EXEC dodaj_osoba 'Krystyna', 'Jarosz', '978376';
EXEC dodaj_osoba 'Marta', 'Ratajczak', '844231';
EXEC dodaj_osoba 'Łukasz', 'Kania', NULL;
EXEC dodaj_osoba 'Mateusz', 'Wojcik', NULL;
EXEC dodaj_osoba 'Beata', 'Kania', '436401';
EXEC dodaj_osoba 'Adam', 'Klimek', NULL;
EXEC dodaj_osoba 'Henryk', 'Bak', NULL;
EXEC dodaj_osoba 'Halina', 'Zięba', NULL;
EXEC dodaj_osoba 'Elzbieta', 'Zięba', NULL;
EXEC dodaj_osoba 'Helena', 'Kania', NULL;
EXEC dodaj_osoba 'Zbigniew', 'Marciniak', NULL;
EXEC dodaj_osoba 'Józef', 'Piątek', '544935';
EXEC dodaj_osoba 'Paweł', 'Klimek', NULL;
EXEC dodaj_osoba 'Ewa', 'Urban', '906814';
EXEC dodaj_osoba 'Jan', 'Kowalik', NULL;
EXEC dodaj_osoba 'Aleksandra', 'Krawczyk', NULL;
EXEC dodaj_osoba 'Grażyna', 'Klimek', NULL;
EXEC dodaj_osoba 'Marta', 'Żak', '412577';
EXEC dodaj_osoba 'Marcin', 'Kolodziej', NULL;
EXEC dodaj_osoba 'Józef', 'Leśniak', '260685';
EXEC dodaj_osoba 'Jakub', 'Stankiewicz', NULL;
EXEC dodaj_osoba 'Małgorzata', 'Przybysz', '135954';
EXEC dodaj_osoba 'Mateusz', 'Nowak', NULL;
EXEC dodaj_osoba 'Michal', 'Wlodarczyk', NULL;
EXEC dodaj_osoba 'Irena', 'Polak', NULL;
EXEC dodaj_osoba 'Ryszard', 'Urban', NULL;
EXEC dodaj_osoba 'Małgorzata', 'Nowak', NULL;
EXEC dodaj_osoba 'Mateusz', 'Wrobel', NULL;
EXEC dodaj_osoba 'Marcin', 'Leśniak', NULL;
EXEC dodaj_osoba 'Anna', 'Jarosz', '185581';
EXEC dodaj_osoba 'Jolanta', 'Olejniczak', NULL;
EXEC dodaj_osoba 'Józef', 'Bednarek', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Dziedzic', NULL;
EXEC dodaj_osoba 'Maciej', 'Cieslak', '237055';
EXEC dodaj_osoba 'Beata', 'Dziedzic', '084771';
EXEC dodaj_osoba 'Marianna', 'Bednarek', '894626';
EXEC dodaj_osoba 'Henryk', 'Kolodziej', '354569';
EXEC dodaj_osoba 'Joanna', 'Mroz', '940113';
EXEC dodaj_osoba 'Karolina', 'Nowak', '704713';
EXEC dodaj_osoba 'Anna', 'Koziol', '590214';
EXEC dodaj_osoba 'Adam', 'Mroz', NULL;
EXEC dodaj_osoba 'Stanisław', 'Mucha', NULL;
EXEC dodaj_osoba 'Piotr', 'Małek', NULL;
EXEC dodaj_osoba 'Wojciech', 'Mucha', '290391';
EXEC dodaj_osoba 'Marcin', 'Przybysz', NULL;
EXEC dodaj_osoba 'Irena', 'Leśniak', NULL;
EXEC dodaj_osoba 'Magdalena', 'Pająk', '807649';
EXEC dodaj_osoba 'Zofia', 'Sowa', '335765';
EXEC dodaj_osoba 'Tadeusz', 'Klimek', NULL;
EXEC dodaj_osoba 'Dorota', 'Wozniak', NULL;
EXEC dodaj_osoba 'Piotr', 'Mazur', '677106';
EXEC dodaj_osoba 'Zbigniew', 'Pawlik', NULL;
EXEC dodaj_osoba 'Tomasz', 'Kruk', NULL;
EXEC dodaj_osoba 'Jadwiga', 'Tomczyk', '457140';
EXEC dodaj_osoba 'Ewa', 'Zajac', NULL;
EXEC dodaj_osoba 'Magdalena', 'Stepien', NULL;
EXEC dodaj_osoba 'Danuta', 'Polak', '958829';
EXEC dodaj_osoba 'Agnieszka', 'Klimek', '288983';
EXEC dodaj_osoba 'Kazimierz', 'Kania', '762812';
EXEC dodaj_osoba 'Grzegorz', 'Zajac', NULL;
EXEC dodaj_osoba 'Janina', 'Zajac', NULL;
EXEC dodaj_osoba 'Grzegorz', 'Czech', NULL;
EXEC dodaj_osoba 'Małgorzata', 'Zięba', NULL;
EXEC dodaj_osoba 'Joanna', 'Świątek', '474693';
EXEC dodaj_osoba 'Helena', 'Mazur', NULL;
EXEC dodaj_osoba 'Beata', 'Sowa', NULL;
EXEC dodaj_osoba 'Joanna', 'Michalak', '155042';
EXEC dodaj_osoba 'Elzbieta', 'Kruk', '525155';
EXEC dodaj_osoba 'Elzbieta', 'Pająk', NULL;
EXEC dodaj_osoba 'Halina', 'Zięba', NULL;
EXEC dodaj_osoba ' Maria', 'Kruk', '330474';
EXEC dodaj_osoba ' Maria', 'Łuczak', '223432';
EXEC dodaj_osoba 'Paweł', 'Mroz', '634039';
EXEC dodaj_osoba 'Halina', 'Łuczak', NULL;
EXEC dodaj_osoba 'Agnieszka', 'Olejniczak', NULL;
EXEC dodaj_osoba 'Barbara', 'Kania', NULL;
EXEC dodaj_osoba 'Janina', 'Wozniak', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Pająk', NULL;
EXEC dodaj_osoba 'Iwona', 'Ratajczak', NULL;
EXEC dodaj_osoba 'Jerzy', 'Marciniak', NULL;
EXEC dodaj_osoba 'Marianna', 'Stankiewicz', NULL;
EXEC dodaj_osoba 'Zbigniew', 'Zajac', NULL;
EXEC dodaj_osoba 'Barbara', 'Zięba', '153888';
EXEC dodaj_osoba 'Barbara', 'Wozniak', NULL;
EXEC dodaj_osoba 'Mateusz', 'Kaczmarek', '055334';
EXEC dodaj_osoba 'Irena', 'Ratajczak', NULL;
EXEC dodaj_osoba 'Mariusz', 'Urban', '664083';
EXEC dodaj_osoba 'Adam', 'Marciniak', NULL;
EXEC dodaj_osoba 'Natalia', 'Bednarek', NULL;
EXEC dodaj_osoba 'Anna', 'Duda', NULL;
EXEC dodaj_osoba 'Teresa', 'Pawlik', NULL;
EXEC dodaj_osoba 'Agnieszka', 'Polak', NULL;
EXEC dodaj_osoba 'Beata', 'Krawczyk', NULL;
EXEC dodaj_osoba 'Zbigniew', 'Lis', NULL;
EXEC dodaj_osoba 'Zofia', 'Pająk', NULL;
EXEC dodaj_osoba 'Irena', 'Szewczyk', NULL;
EXEC dodaj_osoba 'Elzbieta', 'Mucha', '724538';
EXEC dodaj_osoba 'Marianna', 'Kruk', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Kot', NULL;
EXEC dodaj_osoba 'Natalia', 'Klimek', NULL;
EXEC dodaj_osoba 'Małgorzata', 'Dudek', NULL;
EXEC dodaj_osoba 'Marianna', 'Bak', '314181';
EXEC dodaj_osoba 'Marianna', 'Kaczmarek', NULL;
EXEC dodaj_osoba 'Katarzyna', 'Kasprzyk', NULL;
EXEC dodaj_osoba 'Ewa', 'Urban', NULL;
EXEC dodaj_osoba 'Halina', 'Kaczmarek', NULL;
EXEC dodaj_osoba 'Iwona', 'Kopeć', '576525';
EXEC dodaj_osoba 'Danuta', 'Bak', NULL;
EXEC dodaj_osoba 'Iwona', 'Kaczmarek', NULL;
EXEC dodaj_osoba 'Ewa', 'Marciniak', NULL;
EXEC dodaj_osoba 'Kamil', 'Zajac', '399145';
EXEC dodaj_osoba 'Ewa', 'Mazur', '379509';
EXEC dodaj_osoba 'Elzbieta', 'Wilk', NULL;
EXEC dodaj_osoba 'Helena', 'Piątek', '372928';
EXEC dodaj_osoba 'Piotr', 'Bednarek', '376245';
EXEC dodaj_osoba 'Ewa', 'Mroz', NULL;
EXEC dodaj_osoba 'Paweł', 'Czech', '161571';
EXEC dodaj_osoba 'Joanna', 'Stankiewicz', '654517';
EXEC dodaj_osoba 'Jacek', 'Tomczyk', '286586';
EXEC dodaj_osoba 'Aleksandra', 'Duda', NULL;
EXEC dodaj_osoba 'Marek', 'Zajac', '687195';
EXEC dodaj_osoba 'Wojciech', 'Kolodziej', '913378';
EXEC dodaj_osoba 'Rafał', 'Leśniak', '956538';
EXEC dodaj_osoba 'Wojciech', 'Kowalik', NULL;
EXEC dodaj_osoba 'Michal', 'Blaszczyk', NULL;
EXEC dodaj_osoba 'Iwona', 'Adamczyk', NULL;
EXEC dodaj_osoba 'Ewa', 'Urban', NULL;
EXEC dodaj_osoba 'Grażyna', 'Żak', '417652';
EXEC dodaj_osoba 'Wojciech', 'Stankiewicz', NULL;
EXEC dodaj_osoba 'Halina', 'Olejniczak', '890545';
EXEC dodaj_osoba 'Józef', 'Nowak', '569428';
EXEC dodaj_osoba 'Irena', 'Wieczorek', '293730';
EXEC dodaj_osoba 'Dariusz', 'Kowalik', NULL;
EXEC dodaj_osoba 'Teresa', 'Michalak', NULL;
EXEC dodaj_osoba 'Krzysztof', 'Mucha', NULL;
EXEC dodaj_osoba 'Katarzyna', 'Pająk', NULL;
EXEC dodaj_osoba 'Marek', 'Cieslak', NULL;
EXEC dodaj_osoba 'Ewa', 'Wojcik', '550917';
EXEC dodaj_osoba 'Mateusz', 'Olejniczak', '817972';
EXEC dodaj_osoba 'Krystyna', 'Duda', '224366';
EXEC dodaj_osoba 'Jerzy', 'Zięba', '916245';
EXEC dodaj_osoba 'Monika', 'Tomczyk', '910192';
EXEC dodaj_osoba 'Mateusz', 'Urban', NULL;
EXEC dodaj_osoba 'Ewa', 'Kaczmarek', NULL;
EXEC dodaj_osoba 'Halina', 'Wlodarczyk', '344209';
EXEC dodaj_osoba 'Helena', 'Kubiak', NULL;
EXEC dodaj_osoba 'Tomasz', 'Bak', '458097';
EXEC dodaj_osoba 'Andrzej', 'Jarosz', NULL;
EXEC dodaj_osoba 'Marta', 'Blaszczyk', NULL;
EXEC dodaj_osoba 'Halina', 'Dziedzic', NULL;
EXEC dodaj_osoba 'Jolanta', 'Kopeć', NULL;
EXEC dodaj_osoba 'Robert', 'Mazur', NULL;
EXEC dodaj_osoba 'Marta', 'Zięba', NULL;
EXEC dodaj_osoba 'Ewa', 'Polak', NULL;
EXEC dodaj_osoba 'Aleksandra', 'Dziedzic', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Bak', '245237';
EXEC dodaj_osoba 'Jolanta', 'Klimek', NULL;
EXEC dodaj_osoba 'Beata', 'Pietrzak', '049613';
EXEC dodaj_osoba 'Zbigniew', 'Tomczyk', NULL;
EXEC dodaj_osoba 'Monika', 'Marciniak', NULL;
EXEC dodaj_osoba 'Ryszard', 'Pawlik', NULL;
EXEC dodaj_osoba ' Maria', 'Dudek', NULL;
EXEC dodaj_osoba 'Marta', 'Wozniak', '664986';
EXEC dodaj_osoba 'Teresa', 'Blaszczyk', NULL;
EXEC dodaj_osoba 'Stanisław', 'Stankiewicz', NULL;
EXEC dodaj_osoba 'Marek', 'Zięba', NULL;
EXEC dodaj_osoba 'Marta', 'Stepien', NULL;
EXEC dodaj_osoba 'Łukasz', 'Wojcik', NULL;
EXEC dodaj_osoba 'Jakub', 'Mroz', NULL;
EXEC dodaj_osoba 'Magdalena', 'Wieczorek', NULL;
EXEC dodaj_osoba 'Dorota', 'Kolodziej', NULL;
EXEC dodaj_osoba 'Mariusz', 'Urban', NULL;
EXEC dodaj_osoba 'Jacek', 'Zajac', NULL;
EXEC dodaj_osoba 'Marcin', 'Cieslak', NULL;
EXEC dodaj_osoba 'Mariusz', 'Kasprzyk', NULL;
EXEC dodaj_osoba 'Maciej', 'Żak', '733443';
EXEC dodaj_osoba 'Monika', 'Cieslak', NULL;
EXEC dodaj_osoba 'Piotr', 'Krawczyk', NULL;
EXEC dodaj_osoba 'Natalia', 'Urban', '304188';
EXEC dodaj_osoba 'Tadeusz', 'Olejniczak', '590759';
EXEC dodaj_osoba 'Grzegorz', 'Zięba', NULL;
EXEC dodaj_osoba 'Iwona', 'Bak', NULL;
EXEC dodaj_osoba 'Iwona', 'Jarosz', NULL;
EXEC dodaj_osoba 'Małgorzata', 'Kozak', NULL;
EXEC dodaj_osoba 'Krzysztof', 'Piątek', '159804';
EXEC dodaj_osoba 'Janina', 'Wieczorek', NULL;
EXEC dodaj_osoba 'Ryszard', 'Marciniak', '967413';
EXEC dodaj_osoba 'Jolanta', 'Kaczmarczyk', NULL;
EXEC dodaj_osoba 'Barbara', 'Cieslak', NULL;
EXEC dodaj_osoba 'Maciej', 'Mroz', NULL;
EXEC dodaj_osoba 'Helena', 'Walczak', '878207';
EXEC dodaj_osoba 'Zbigniew', 'Czaja', NULL;
EXEC dodaj_osoba 'Jerzy', 'Leśniak', NULL;
EXEC dodaj_osoba 'Michal', 'Wlodarczyk', NULL;
EXEC dodaj_osoba 'Stanisław', 'Bednarek', NULL;
EXEC dodaj_osoba 'Stanisław', 'Przybysz', NULL;
EXEC dodaj_osoba 'Michal', 'Mucha', NULL;
EXEC dodaj_osoba 'Józef', 'Mucha', '166460';
EXEC dodaj_osoba 'Mateusz', 'Adamczyk', '347301';
EXEC dodaj_osoba 'Łukasz', 'Blaszczyk', '760658';
EXEC dodaj_osoba 'Anna', 'Kaczmarczyk', NULL;
EXEC dodaj_osoba 'Magdalena', 'Stankiewicz', NULL;
EXEC dodaj_osoba 'Jerzy', 'Czaja', NULL;
EXEC dodaj_osoba 'Zofia', 'Kozak', NULL;
EXEC dodaj_osoba 'Magdalena', 'Nowak', '367106';
EXEC dodaj_osoba 'Rafał', 'Kruk', '236033';
EXEC dodaj_osoba 'Magdalena', 'Koziol', NULL;
EXEC dodaj_osoba 'Aleksandra', 'Matysiak', NULL;
EXEC dodaj_osoba 'Zbigniew', 'Bak', NULL;
EXEC dodaj_osoba 'Elzbieta', 'Kot', NULL;
EXEC dodaj_osoba 'Mariusz', 'Szewczyk', NULL;
EXEC dodaj_osoba 'Jerzy', 'Czech', NULL;
EXEC dodaj_osoba 'Michal', 'Tomczak', '073795';
EXEC dodaj_osoba 'Zofia', 'Stasiak', '089315';
EXEC dodaj_osoba 'Grażyna', 'Wlodarczyk', NULL;
EXEC dodaj_osoba 'Dariusz', 'Zajac', NULL;
EXEC dodaj_osoba 'Natalia', 'Zięba', '589746';
EXEC dodaj_osoba 'Małgorzata', 'Przybysz', NULL;
EXEC dodaj_osoba 'Karolina', 'Mroz', '830717';
EXEC dodaj_osoba 'Marta', 'Mazur', NULL;
EXEC dodaj_osoba 'Zbigniew', 'Kopeć', NULL;
EXEC dodaj_osoba 'Tomasz', 'Pająk', NULL;
EXEC dodaj_osoba 'Paweł', 'Jarosz', '869942';
EXEC dodaj_osoba 'Elzbieta', 'Bak', '019953';
EXEC dodaj_osoba 'Jan', 'Czaja', NULL;
EXEC dodaj_osoba 'Andrzej', 'Olejniczak', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Kubiak', NULL;
EXEC dodaj_osoba 'Michal', 'Leśniak', NULL;
EXEC dodaj_osoba 'Jerzy', 'Bak', '449327';
EXEC dodaj_osoba 'Halina', 'Sowa', NULL;
EXEC dodaj_osoba 'Danuta', 'Ratajczak', '010491';
EXEC dodaj_osoba 'Karolina', 'Mroz', NULL;
EXEC dodaj_osoba ' Maria', 'Świątek', '290197';
EXEC dodaj_osoba 'Adam', 'Tomczyk', '293996';
EXEC dodaj_osoba 'Monika', 'Walczak', NULL;
EXEC dodaj_osoba 'Kamil', 'Kaczmarek', NULL;
EXEC dodaj_osoba 'Marta', 'Mroz', NULL;
EXEC dodaj_osoba 'Teresa', 'Świątek', NULL;
EXEC dodaj_osoba 'Dorota', 'Świątek', NULL;
EXEC dodaj_osoba 'Piotr', 'Kruk', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Mucha', NULL;
EXEC dodaj_osoba 'Łukasz', 'Mroz', NULL;
EXEC dodaj_osoba 'Iwona', 'Mucha', '678088';
EXEC dodaj_osoba 'Andrzej', 'Adamczyk', '030720';
EXEC dodaj_osoba 'Marianna', 'Klimek', NULL;
EXEC dodaj_osoba 'Adam', 'Bak', '678890';
EXEC dodaj_osoba 'Joanna', 'Urban', NULL;
EXEC dodaj_osoba 'Marianna', 'Stankiewicz', '213548';
EXEC dodaj_osoba 'Monika', 'Baran', NULL;
EXEC dodaj_osoba 'Grzegorz', 'Polak', NULL;
EXEC dodaj_osoba ' Maria', 'Baran', NULL;
EXEC dodaj_osoba 'Stanisław', 'Świątek', NULL;
EXEC dodaj_osoba 'Kazimierz', 'Zięba', '304852';
EXEC dodaj_osoba 'Tomasz', 'Kozak', '531670';
EXEC dodaj_osoba 'Piotr', 'Kazmierczak', NULL;
EXEC dodaj_osoba 'Jacek', 'Świątek', NULL;
EXEC dodaj_osoba 'Robert', 'Ratajczak', '263002';
EXEC dodaj_osoba 'Ewa', 'Pawlik', NULL;
EXEC dodaj_osoba 'Adam', 'Polak', '688551';
EXEC dodaj_osoba 'Piotr', 'Ratajczak', NULL;
EXEC dodaj_osoba 'Jacek', 'Pająk', NULL;
EXEC dodaj_osoba 'Łukasz', 'Stepien', NULL;
EXEC dodaj_osoba 'Tomasz', 'Kolodziej', NULL;
EXEC dodaj_osoba 'Michal', 'Szewczyk', NULL;
EXEC dodaj_osoba 'Paweł', 'Mazur', '437558';
EXEC dodaj_osoba 'Teresa', 'Krawczyk', '192782';
EXEC dodaj_osoba 'Jerzy', 'Ratajczak', NULL;
EXEC dodaj_osoba 'Iwona', 'Kaczmarek', '710726';
EXEC dodaj_osoba 'Aleksandra', 'Duda', '314664';
EXEC dodaj_osoba 'Joanna', 'Duda', '803487';
EXEC dodaj_osoba 'Halina', 'Pająk', '530643';
EXEC dodaj_osoba 'Danuta', 'Wojcik', NULL;
EXEC dodaj_osoba 'Teresa', 'Przybysz', NULL;
EXEC dodaj_osoba 'Iwona', 'Kazmierczak', '196267';
EXEC dodaj_osoba 'Anna', 'Krawczyk', NULL;
EXEC dodaj_osoba 'Krystyna', 'Cieslak', NULL;
EXEC dodaj_osoba 'Halina', 'Cieslak', NULL;
EXEC dodaj_osoba 'Halina', 'Olejniczak', NULL;
EXEC dodaj_osoba 'Wojciech', 'Urban', NULL;
EXEC dodaj_osoba 'Rafał', 'Piątek', NULL;
EXEC dodaj_osoba 'Grzegorz', 'Dudek', '371816';
EXEC dodaj_osoba 'Dorota', 'Kazmierczak', NULL;
EXEC dodaj_osoba 'Wojciech', 'Kania', '535525';
EXEC dodaj_osoba 'Danuta', 'Walczak', '177781';
EXEC dodaj_osoba 'Kamil', 'Żak', '065033';
EXEC dodaj_osoba 'Kazimierz', 'Kot', NULL;
EXEC dodaj_osoba 'Zbigniew', 'Czaja', NULL;
EXEC dodaj_osoba 'Karolina', 'Matysiak', NULL;
EXEC dodaj_osoba 'Dorota', 'Piątek', NULL;
EXEC dodaj_osoba 'Wojciech', 'Kolodziej', '489140';
EXEC dodaj_osoba 'Agnieszka', 'Kazmierczak', '672491';
EXEC dodaj_osoba 'Dariusz', 'Lis', '054630';
EXEC dodaj_osoba 'Ewa', 'Zajac', NULL;
EXEC dodaj_osoba 'Jadwiga', 'Dziedzic', '816369';
EXEC dodaj_osoba 'Mariusz', 'Świątek', '087581';
EXEC dodaj_osoba 'Maciej', 'Jarosz', NULL;
EXEC dodaj_osoba 'Dorota', 'Pawlik', '064405';

